openapi: '3.0.2'
info:
  title: MUJI MOCK - Products API DOCs
  version: '1.0'
servers:
  # - url: https://white-100.online/api/1.0
  - url: http://localhost:5000/api/1.0
paths:
  /products/details:
    get:
      tags:
        - products
      description: 獲取產品詳細資訊
      responses:
        '200':
          description: OK

      parameters:
        - name: id
          in: query
          schema:
            type: integer
            default: 201807202140
          required: true

  /products/variant:
    get:
      tags:
        - products
      description: 獲取特定產品規格的資訊
      responses:
        '200':
          description: OK
      parameters:
        - name: id
          in: query
          schema:
            type: integer
            default: 1
          required: true

  /products/category:
    get:
      tags:
        - products
      description: 獲取不同類別的產品列表
      responses:
        '200':
          description: OK
      parameters:
        - name: category
          in: query
          schema:
            type: string
            default: 'clothes'
          required: true

  /admin/product:
    post:
      tags:
        - admin
      description: 創建產品，自由創建兩種規格
      responses:
        '200':
          description: OK
